name: 'Web Vitals'
description: 'Audit SEO, Accessibility and Performance'

runs:
  using: 'composite'
  steps:
    - uses: ./.github/actions/setup-project

    - uses: actions/download-artifact@v8
      with:
        name: astro-build-folder
        path: ${{ env.BUILD_FOLDER }}

    - shell: bash
      run: npm run lighthouse:local

    - uses: actions/upload-artifact@v7
      if: failure()
      with:
        name: lighthouse-report
        path: lighthouse-report/
        retention-days: 7
