name: 'Restore Project Environment'
description: 'Setup NodeJS and Restore node_modules from cache'
runs:
  using: "composite"
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v6
      with:
        node-version: '24.14.1'

    - name: Restore node_modules from Cache
      uses: actions/cache@v4
      with:
        path: node_modules
        # On utilise exactement la même clé partout
        key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
