name: build

on:
  workflow_call:

jobs:
  astro:
    name: Astro
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Restore Env & Node
        uses: ./.github/actions/setup-project

      - name: Build application
        run: npm run build
        env:
          APP_CV_PDF_NAME_FILE: ${{ vars.APP_CV_PDF_NAME_FILE }}
          APP_ID_GITHUB: ${{ vars.APP_ID_GITHUB }}
          APP_ID_LINKEDIN: ${{ vars.APP_ID_LINKEDIN }}
          APP_MAILTO_EMAIL: ${{ vars.APP_MAILTO_EMAIL }}
          APP_PHONE_NUMBER: ${{ vars.APP_PHONE_NUMBER }}

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v7
        with:
          name: astro-build-folder
          path: ${{ vars.APP_BUILD_FOLDER }}
          retention-days: 1
