name: build

on:
  workflow_call:

jobs:
  astro:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup project
        uses: ./.github/actions/setup-project

      - name: Build application
        run: npm run build
