name: deployment

on:
  workflow_call:
    secrets:
      SCALEWAY_ACCESS_KEY:
        required: true
      SCALEWAY_SECRET_KEY:
        required: true
      SCALEWAY_BUCKET_DEVELOP:
        required: true

jobs:
  scaleway:
    name: Deploy on Scaleway
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.SCALEWAY_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.SCALEWAY_SECRET_KEY }}
      AWS_DEFAULT_REGION: fr-par
      BUCKET_NAME: ${{ secrets.SCALEWAY_BUCKET_PROD }}
      CV_PDF_NAME_FILE: ${{ vars.CV_PDF_NAME_FILE }}
      ID_GITHUB: ${{ vars.ID_GITHUB }}
      ID_LINKEDIN: ${{ vars.ID_LINKEDIN }}
      MAILTO_EMAIL: ${{ vars.MAILTO_EMAIL }}
      PHONE_NUMBER: ${{ vars.PHONE_NUMBER }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Restore Env & Node
        uses: ./.github/actions/setup-project

      - name: Build application
        run: npm run build

      - name: Deploy to Scaleway Prod
        run: |
          aws s3 sync dist/ s3://$BUCKET_NAME --endpoint-url https://s3.fr-par.scw.cloud --delete --acl public-read
