name: web vitals

on:
  workflow_call:

env:
  BUILD_FOLDER: ${{ vars.APP_BUILD_FOLDER }}

jobs:
  develop:
    name: Develop
    if: github.ref == 'refs/heads/develop' && success()
    runs-on: ubuntu-latest
    environment: develop

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Run Composite Action
        uses: ./.github/actions/web-vitals

  prod:
    name: Production
    if: github.ref == 'refs/heads/master' && success()
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Run Composite Action
        uses: ./.github/actions/web-vitals
