name: CD

on:
  push:
    branches: ['master', 'develop']
    paths-ignore:
      - '.vscode/**'
      - 'docs/**'
      - 'tests/**'
      - '.editorconfig'
      - '.gitignore'
      - '.lighthouserc.json'
      - '.prettier*'
      - 'README.md'
      - 'eslint.config.mjs'
      - 'playwright.config.ts'
      - 'vitest.config.ts'

jobs:
  run-build:
    name: Build
    uses: ./.github/workflows/build.yml

  run-deployment:
    name: Deployment
    needs: run-build
    uses: ./.github/workflows/cd-deployment.yml
    secrets:
      SCALEWAY_ACCESS_KEY: ${{ secrets.SCALEWAY_ACCESS_KEY }}
      SCALEWAY_SECRET_KEY: ${{ secrets.SCALEWAY_SECRET_KEY }}
      SCALEWAY_BUCKET_DEVELOP: ${{ secrets.SCALEWAY_BUCKET_DEVELOP }}
      SCALEWAY_BUCKET_PROD: ${{ secrets.SCALEWAY_BUCKET_PROD }}
