name: checks

on:
  workflow_call:

jobs:
  tsc:
    runs-on: ubuntu-latest

    steps:
      - name: Setup project
        uses: ./.github/actions/setup-project

      - name: Check typescript
        run: npm run check:tsc

  astro:
    runs-on: ubuntu-latest

    steps:
      - name: Setup project
        uses: ./.github/actions/setup-project

      - name: Check Astro
        run: npm run check:astro
