name: deploy

on:
  workflow_call:
    secrets:
      HOSTING_PROVIDER_ACCESS_KEY:
        required: true
      HOSTING_PROVIDER_SECRET_KEY:
        required: true
      HOSTING_PROVIDER_BUCKET_PREVIEW:
        required: true

jobs:
  deploy_on_preview:
    name: Preview
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.HOSTING_PROVIDER_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.HOSTING_PROVIDER_SECRET_KEY }}
      AWS_DEFAULT_REGION: fr-par
      BUCKET_NAME: ${{ secrets.HOSTING_PROVIDER_BUCKET_PREVIEW }}
      BUILD_FOLDER: ${{ vars.APP_BUILD_FOLDER }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Restore Env & Node
        uses: ./.github/actions/setup-project

      - name: Download Build Artifact
        uses: actions/download-artifact@v8
        with:
          name: astro-build-folder
          path: ${{ vars.APP_BUILD_FOLDER }}

      - name: Deploy to Preview Bucket
        run: |
          aws s3 sync $BUILD_FOLDER s3://$BUCKET_NAME --endpoint-url https://s3.fr-par.scw.cloud --delete
