name: deploy

on:
  workflow_call:
    secrets:
      HOSTING_PROVIDER_ACCESS_KEY:
        required: true
      HOSTING_PROVIDER_SECRET_KEY:
        required: true
      HOSTING_PROVIDER_BUCKET_PREVIEW:
        required: true
      HOSTING_PROVIDER_ENDPOINT_URL:
        required: true
      HOSTING_PROVIDER_DEFAULT_REGION:
        required: true

jobs:
  deploy_on_preview:
    name: Preview
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.HOSTING_PROVIDER_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.HOSTING_PROVIDER_SECRET_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.HOSTING_PROVIDER_DEFAULT_REGION }}
      BUCKET_NAME: ${{ secrets.HOSTING_PROVIDER_BUCKET_PREVIEW }}
      BUILD_FOLDER: ${{ vars.APP_BUILD_FOLDER }}
      ENDPOINT_URL: ${{ secrets.HOSTING_PROVIDER_ENDPOINT_URL }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Download Build Artifact
        uses: actions/download-artifact@v8
        with:
          name: astro-build-folder
          path: ${{ env.BUILD_FOLDER }}

      - name: Deploy to Preview Bucket
        run: |
          aws s3 sync $BUILD_FOLDER/ s3://$BUCKET_NAME --endpoint-url $ENDPOINT_URL --delete
