name: linter

on:
  workflow_call:

jobs:
  local:
    name: Local Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Run Oxlint
        run: npx oxlint

      - name: Synchronize Astro Types
        run: npx astro sync

      - name: Check TypeScript
        run: npx tsc

      - name: Check Astro
        run: npx astro check

      - name: Run ESLint in strict mode
        run: npx eslint --max-warnings=0
