name: production

on:
  workflow_call:

jobs:
  build-and-e2e:
    name: Build & End-To-End Tests
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      CV_PDF_NAME_FILE: ${{ vars.CV_PDF_NAME_FILE }}
      ID_GITHUB: ${{ vars.ID_GITHUB }}
      ID_LINKEDIN: ${{ vars.ID_LINKEDIN }}
      MAILTO_EMAIL: ${{ vars.MAILTO_EMAIL }}
      PHONE_NUMBER: ${{ vars.PHONE_NUMBER }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Restore Env & Node
        uses: ./.github/actions/setup-project

      - name: Build application
        run: npm run build

      #      - name: Install Playwright Browsers & Linux System Deps
      #        run: npx playwright install --with-deps
      #
      #      - name: Run Playwright tests
      #        run: npm run test:e2e
      #        env:
      #          CI: true
      #
      #      - name: Upload Playwright Report (On Failure Only)
      #        uses: actions/upload-artifact@v7
      #        if: failure()
      #        with:
      #          name: playwright-report
      #          path: playwright-report/
      #          retention-days: 7

      - name: Audit SEO & Performance (Lighthouse)
        run: npm run lighthouse

      - name: Upload Lighthouse Report (On Failure Only)
        uses: actions/upload-artifact@v7
        if: failure()
        with:
          name: lighthouse-report
          path: lighthouse-report/
          retention-days: 7
