name: quality

on:
  workflow_call:

jobs:
  checks:
    name: Local Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Restore Env & Node
        uses: ./.github/actions/setup-project

      - name: Check typescript
        run: npm run check:tsc

      - name: Check Astro
        run: npm run check:astro

      - name: Run ESLint in strict mode
        run: npm run lint:strict
