name: smoke tests lv1

on:
  workflow_call:
    inputs:
      playwright-version:
        required: true
        type: string
    secrets:
      HOSTING_PROVIDER_BASE_URL:
        required: true

jobs:
  playwright:
    name: Playwright
    runs-on: ubuntu-latest

    container:
      image: mcr.microsoft.com/playwright:v${{ inputs.playwright-version }}-noble

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Run Smoke Tests Lv1 in preview environment
        uses: ./.github/actions/tests-smoke
        with:
          playwright-tag: '@smoke-lv1'
        env:
          BUILD_FOLDER: ${{ vars.APP_BUILD_FOLDER }}
