name: e2e tests

on:
  workflow_call:
    inputs:
      base_url:
        description: 'target URL (keep empty for local tests)'
        required: false
        type: string
        default: ''

jobs:
  playwright:
    name: Playwright
    runs-on: ubuntu-latest
    environment: ${{ inputs.base_url == '' && 'post-build' || '' }}
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Restore Env & Node
        uses: ./.github/actions/setup-project

      - name: Download Build Artifact
        if: ${{ inputs.base_url == '' }}
        uses: actions/download-artifact@v8
        with:
          name: astro-build-folder
          path: ${{ vars.APP_BUILD_FOLDER }}

      - name: Install Playwright Browsers & Linux System Deps
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npm run test:e2e
        env:
          CI: true
          PLAYWRIGHT_BASE_URL: ${{ inputs.base_url }}
          APP_CV_PDF_NAME_FILE: ${{ vars.APP_CV_PDF_NAME_FILE }}
          APP_ID_GITHUB: ${{ vars.APP_ID_GITHUB }}
          APP_ID_LINKEDIN: ${{ vars.APP_ID_LINKEDIN }}
          APP_MAILTO_EMAIL: ${{ vars.APP_MAILTO_EMAIL }}
          APP_PHONE_NUMBER: ${{ vars.APP_PHONE_NUMBER }}

      - name: Upload Playwright Report (On Failure Only)
        uses: actions/upload-artifact@v7
        if: failure()
        with:
          name: ${{ inputs.base_url != '' && 'playwright-report-prod' || 'playwright-report-local' }}
          path: playwright-report/
          retention-days: 7
