name: tests

on:
  workflow_call:

jobs:
#  units:
#    name: Units
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v6
#
#      - name: Restore Env & Node
#        uses: ./.github/actions/setup-project
#
#      - name: Run tests with coverage
#        run: npm run test:units:cov

  e2e:
    name: End-To-End
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      ID_GITHUB: ${{ vars.ID_GITHUB }}
      ID_LINKEDIN: ${{ vars.ID_LINKEDIN }}
      MAILTO_EMAIL: ${{ vars.MAILTO_EMAIL }}
      PHONE_NUMBER: ${{ vars.PHONE_NUMBER }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Restore Env & Node
        uses: ./.github/actions/setup-project

      - name: Build Astro Project
        run: npm run build

      - name: Install Playwright Browsers & Linux System Deps
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npm run test:e2e
        env:
          CI: true

      - name: Upload Playwright Report (On Failure Only)
        uses: actions/upload-artifact@v7
        if: failure()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7
