name: e2e tests

on:
  workflow_call:

jobs:
  setup-version:
    name: Get Playwright Version
    runs-on: ubuntu-latest

    outputs:
      playwright-version: ${{ steps.get-version.outputs.version }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Get Playwright version
        id: get-version
        run: |
          VERSION=$(node -p "require('./package.json').devDependencies['@playwright/test']" | sed 's/[^0-9.]//g')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

  playwright:
    name: Playwright
    needs: setup-version
    runs-on: ubuntu-latest
    environment: post-build

    container:
      image: mcr.microsoft.com/playwright:v${{ needs.setup-version.outputs.playwright-version }}-noble

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Restore Env & Node
        uses: ./.github/actions/setup-project

      - name: Download Build Artifact
        uses: actions/download-artifact@v8
        with:
          name: astro-build-folder
          path: ${{ vars.APP_BUILD_FOLDER }}

      - name: Run Playwright tests
        run: npm run test:e2e
        env:
          CI: true
          HOME: /root
          DOCKER_CONFIG: /tmp/.docker
          APP_CV_PDF_NAME_FILE: ${{ vars.APP_CV_PDF_NAME_FILE }}
          APP_ID_GITHUB: ${{ vars.APP_ID_GITHUB }}
          APP_ID_LINKEDIN: ${{ vars.APP_ID_LINKEDIN }}
          APP_MAILTO_EMAIL: ${{ vars.APP_MAILTO_EMAIL }}
          APP_PHONE_NUMBER: ${{ vars.APP_PHONE_NUMBER }}

      - name: Upload Playwright Report (On Failure Only)
        uses: actions/upload-artifact@v7
        if: failure()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7
