name: web vitals

on:
  workflow_call:

jobs:
  lighthouse:
    name: Lighthouse
    runs-on: ubuntu-latest
    environment: post-build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Run Composite Action
        uses: ./.github/actions/web-vitals
        env:
          BUILD_FOLDER: ${{ vars.APP_BUILD_FOLDER }}
