name: CI

on:
  pull_request:
    branches:
      - '**'
    paths-ignore:
      - '.vscode/**'
      - 'docs/**'
      - '.editorconfig'
      - '.gitignore'
      - 'README.md'

jobs:
  run-build:
    name: Build
    uses: ./.github/workflows/build.yml

#  run-linter:
#    name: Linter
#    uses: ./.github/workflows/ci-linter.yml
#
#  run-unit-tests:
#    name: Unit Tests
#    uses: ./.github/workflows/ci-unit-tests.yml
#
#  run-e2e-tests:
#    name: E2E Tests
#    needs: run-build
#    uses: ./.github/workflows/ci-tests-e2e.yml
#
#  run-a11y-and-seo:
#    name: SEO & Accessibility
#    needs: run-build
#    uses: ./.github/workflows/ci-seo-and-a11y.yml

  run-deployment:
    name: Deployment
    needs: run-build
    uses: ./.github/workflows/ci-deploy.yml
    secrets:
      SCALEWAY_ACCESS_KEY: ${{ secrets.SCALEWAY_ACCESS_KEY }}
      SCALEWAY_SECRET_KEY: ${{ secrets.SCALEWAY_SECRET_KEY }}
      SCALEWAY_BUCKET_PREVIEW: ${{ secrets.SCALEWAY_BUCKET_PREVIEW }}
