name: Linter

on:
  pull_request:
    branches:
      - '**'
    paths-ignore:
      - '.vscode/**'
      - 'docs/**'
      - '.editorconfig'
      - '.env.example'
      - '.gitignore'
      - 'README.md'

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: '24.14.1'

      - name: Install dependencies
        run: npm install

      - name: Run ESLint in strict mode
        run: npm run lint:strict
