name: lint

on:
  pull_request:
    branches:
      - '**'

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: '24.14.1'

      - name: Install dependencies
        run: npm install

      - name: Run ESLint in strict mode
        if: github.ref == 'refs/heads/master'
        run: npm run lint:strict

      - name: Run ESLint in default mode
        if: github.ref != 'refs/heads/master'
        run: npm run lint
