name: 'Smoke Tests'
description: 'Run Smoke E2E Playwright Tests'

inputs:
  playwright-tag:
    description: 'Playwright tag used to filter E2E tests to run'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Restore Env & Node
      uses: ./.github/actions/setup-project

    - name: Download Build Artifact
      uses: actions/download-artifact@v8
      with:
        name: astro-build-folder
        path: ${{ env.BUILD_FOLDER }}

    - name: Run ${{ inputs.playwright-tag }} E2E Playwright Tests with tag
      run: npm run test:e2e:tag -- ${{ inputs.playwright-tag }}
      shell: bash
      env:
        CI: true
        HOME: /root
        DOCKER_CONFIG: /tmp/.docker
        APP_CV_PDF_NAME_FILE: ${{ env.APP_CV_PDF_NAME_FILE }}
        APP_ID_GITHUB: ${{ env.APP_ID_GITHUB }}
        APP_ID_LINKEDIN: ${{ env.APP_ID_LINKEDIN }}
        APP_MAILTO_EMAIL: ${{ env.APP_MAILTO_EMAIL }}
        APP_PHONE_NUMBER: ${{ env.APP_PHONE_NUMBER }}
        PLAYWRIGHT_BASE_URL: ${{ env.HOSTING_PROVIDER_BASE_URL }}

    - name: Upload Playwright Report (On Failure Only)
      uses: actions/upload-artifact@v7
      if: failure()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 7
